export default Strings = {
  continue: 'Continue',
  welcome: 'Welcome',
  get_started: 'Lets Get Started',
  enter_email: 'Enter your official email address',
  email: 'Email address',
  full_name: 'Full name',
  mobile_number: 'Mobile number',
  phone_number: 'Phone number',
  rank: 'Rank',
  id: 'ID',
  Vessel: 'Enter Vessel Name',
  Date: 'Enter Date',
  Time: 'Enter Time',
  Flight: 'Enter Flight Details',
  otp_verification: 'OTP Verification',
  otp_subtitle: 'Please check your mail for the verification code',
  verify: 'Verify',
  fill_details: 'Please fill the details and create account',
  manager_email: 'Manager Email',
};
