export default Endpoints = {
  Login: '/api/coordinators/signup',
  Validate: '/api/coordinators/login',
  Details: '/api/coordinators/',
  VechicleModel: '/api/vehicles/models',
  PostBookings: '/api/bookings/',
  UpdateBookingStatus: '/api/organizers/bookings/status',
  Bookings: '/api/coordinators/',
  GuestBookings: '/api/coordinators/bookings',
  DriverDetails: '/api/vendors/bookings',
  CostCenters: '/api/cost-centres',
  FcmToken: '/api/devices/fcm-token',
  Invoices: '/api/invoices/client/presigned_url',
  VendorCities: '/api/vendors/cities',
  GuestDetails: '/api/guests',
  PostHotelBooking: '/api/hotel_bookings/',
  GetHotelBooking: '/api/coordinators/hotel_bookings',
  SendNotification: '/api/send-push-notification',
  GetCustomToken: '/api/firebase/generate-token',
};
