"""removed_fcm_token_column

Revision ID: 0c0adc36ebac
Revises: ad7f49dc70f4
Create Date: 2024-04-02 07:43:28.019551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c0adc36ebac'
down_revision: Union[str, None] = 'ad7f49dc70f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_driver_scheduled_messages_id', table_name='driver_scheduled_messages')
    op.drop_table('driver_scheduled_messages')
    op.drop_column('booking_logs', 'message_id')
    op.drop_column('coordinators', 'fcm_token')
    op.drop_column('organizers', 'fcm_token')
    op.drop_column('vendors', 'fcm_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('fcm_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('organizers', sa.Column('fcm_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('coordinators', sa.Column('fcm_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('booking_logs', sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('driver_scheduled_messages',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('scheduled_message_sid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cdate', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('mdate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='driver_scheduled_messages_booking_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='driver_scheduled_messages_pkey')
    )
    op.create_index('ix_driver_scheduled_messages_id', 'driver_scheduled_messages', ['id'], unique=False)
    # ### end Alembic commands ###
