"""Add po number in bookings table

Revision ID: 162b067e4f75
Revises: 92632c65d990
Create Date: 2025-06-26 06:33:04.097867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '162b067e4f75'
down_revision: Union[str, None] = '92632c65d990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('po_number', sa.String(), server_default='NA', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'po_number')
    # ### end Alembic commands ###
