"""add_hotel_booking_edit_requests_table

Revision ID: 16ee65e69a0d
Revises: cd7bb8905c9f
Create Date: 2024-09-30 07:53:19.001894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16ee65e69a0d'
down_revision: Union[str, None] = 'cd7bb8905c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_booking_edit_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['hotel_bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hotel_bookings', sa.Column('related_booking_id', sa.String(), nullable=True))
    op.add_column('booking_logs', sa.Column('cc_recipients', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('hotel_booking_guests', sa.Column('cc_recipients', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel_booking_guests', 'cc_recipients')
    op.drop_column('booking_logs', 'cc_recipients')
    op.drop_column('hotel_bookings', 'related_booking_id')
    op.drop_table('hotel_booking_edit_requests')
    # ### end Alembic commands ###
