"""add_tables_for_hotel_booking_flow

Revision ID: 238353cc28b8
Revises: 60cf5bc5aa1b
Create Date: 2024-09-10 05:55:42.980861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '238353cc28b8'
down_revision: Union[str, None] = 'b0ed2e06114c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bid', sa.String(), nullable=False),
    sa.Column('booking_type', sa.String(), nullable=False),
    sa.Column('no_of_adults', sa.Integer(), nullable=False),
    sa.Column('no_of_children', sa.Integer(), nullable=False),
    sa.Column('coordinator_id', sa.BigInteger(), nullable=True),
    sa.Column('organizer_id', sa.BigInteger(), nullable=True),
    sa.Column('vendor_id', sa.BigInteger(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('cost_centre_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mdate', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coordinator_id'], ['coordinators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_centre_id'], ['cost_centres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_bookings_id'), 'hotel_bookings', ['id'], unique=True)
    op.create_table('hotel_booking_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mdate', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['hotel_bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_booking_guests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), nullable=False),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('vessel_name', sa.String(), nullable=True),
    sa.Column('internal_id', sa.String(), nullable=True),
    sa.Column('guest_message_sid', sa.String(), nullable=True),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['hotel_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_booking_guests_id'), 'hotel_booking_guests', ['id'], unique=False)
    op.create_table('hotel_booking_room_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('no_of_rooms', sa.Integer(), nullable=False),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['hotel_bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_booking_room_details_id'), 'hotel_booking_room_details', ['id'], unique=False)
    op.add_column('vendors', sa.Column('is_third_party', sa.Boolean(), nullable=False, server_default=sa.text("'FALSE'")))
    op.add_column('vendors', sa.Column('vendor_type', sa.String(), nullable=False, server_default=sa.text("'cab'")))
    op.drop_column('guests', 'check_in')
    op.drop_column('guests', 'check_out')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('check_in', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('guests', sa.Column('check_out', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('vendors', 'vendor_type')
    op.drop_index(op.f('ix_hotel_booking_room_details_id'), table_name='hotel_booking_room_details')
    op.drop_table('hotel_booking_room_details')
    op.drop_index(op.f('ix_hotel_booking_guests_id'), table_name='hotel_booking_guests')
    op.drop_table('hotel_booking_guests')
    op.drop_table('hotel_booking_events')
    op.drop_index(op.f('ix_hotel_bookings_id'), table_name='hotel_bookings')
    op.drop_table('hotel_bookings')
    # ### end Alembic commands ###
