"""add_unique_constraint_in_vendor_invoice

Revision ID: 24a5d710e3ae
Revises: 6e696a7b0ef1
Create Date: 2026-01-12 16:58:29.691320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a5d710e3ae'
down_revision: Union[str, None] = '6e696a7b0ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_vendor_invoices_booking_id",
        "vendor_invoices",
        ["booking_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_vendor_invoices_booking_id",
        "vendor_invoices",
        type_="unique"
    )
    # ### end Alembic commands ###
