"""add_bid_column_in_bookings_table

Revision ID: 2a0eaccad4ad
Revises: 2aee1b3f8e97
Create Date: 2024-04-25 11:02:13.078016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0eaccad4ad'
down_revision: Union[str, None] = '2aee1b3f8e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE bid_seq START 1 INCREMENT 1;")
    op.add_column(
        'bookings',
        sa.Column('bid', sa.String(), server_default=sa.text("('BID' || nextval('bid_seq'))"))
    )

def downgrade()-> None:
    op.drop_column('bookings', 'bid')
    op.execute("DROP SEQUENCE bid_seq")
