"""update_vendor_invoices_table

Revision ID: 2be879f5fe8a
Revises: 0c0adc36ebac
Create Date: 2024-04-03 17:55:27.013933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be879f5fe8a'
down_revision: Union[str, None] = '0c0adc36ebac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_invoices', sa.Column('event', sa.String(), nullable=False))
    op.add_column('vendor_invoices', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('vendor_invoices', sa.Column('miscellaneous', sa.Float(), nullable=True))
    op.add_column('vendor_invoices', sa.Column('parking_and_toll', sa.Float(), nullable=True))
    op.add_column('vendor_invoices', sa.Column('driver_charge', sa.Float(), nullable=False))
    op.add_column('vendor_invoices', sa.Column('base_fare', sa.Float(), nullable=False))
    op.add_column('vendor_invoices', sa.Column('discount_percent', sa.Float(), nullable=True))
    op.add_column('vendor_invoices', sa.Column('extra_kms', sa.Float(), nullable=True))
    op.add_column('vendor_invoices', sa.Column('extra_hrs', sa.Float(), nullable=True))
    op.alter_column('vendor_invoices', 'invoice_amount',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Float(),
                    existing_nullable=False,
                    postgresql_using='invoice_amount::double precision')
    op.drop_column('vendor_invoices', 'cgst_amount')
    op.drop_column('vendor_invoices', 'sgst_amount')
    op.drop_column('vendor_invoices', 'invoice_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_invoices', sa.Column('invoice_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendor_invoices', sa.Column('sgst_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('vendor_invoices', sa.Column('cgst_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('vendor_invoices', 'invoice_amount',
                    existing_type=sa.Float(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.drop_column('vendor_invoices', 'extra_hrs')
    op.drop_column('vendor_invoices', 'extra_kms')
    op.drop_column('vendor_invoices', 'discount_percent')
    op.drop_column('vendor_invoices', 'base_fare')
    op.drop_column('vendor_invoices', 'driver_charge')
    op.drop_column('vendor_invoices', 'parking_and_toll')
    op.drop_column('vendor_invoices', 'miscellaneous')
    op.drop_column('vendor_invoices', 'comment')
    op.drop_column('vendor_invoices', 'event')
    # ### end Alembic commands ###
