"""modified invoices table

Revision ID: 303d53166552
Revises: 4e9731d40d13
Create Date: 2024-06-18 07:11:49.351156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303d53166552'
down_revision: Union[str, None] = '4e9731d40d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'comment', new_column_name='description')
    op.alter_column('invoices', 'overridden_amount', new_column_name='taxable_sub_total')
    op.add_column('invoices', sa.Column('non_taxable_sub_total', sa.DOUBLE_PRECISION(precision=53), server_default='0', nullable=False))
    op.add_column('invoices', sa.Column('cgst_amount', sa.DOUBLE_PRECISION(precision=53), server_default='0', nullable=False))
    op.add_column('invoices', sa.Column('sgst_amount', sa.DOUBLE_PRECISION(precision=53), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'description', new_column_name='comment')
    op.alter_column('invoices', 'taxable_sub_total', new_column_name='overridden_amount')
    op.drop_column('invoices', 'non_taxable_sub_total')
    op.drop_column('invoices', 'cgst_amount')
    op.drop_column('invoices', 'sgst_amount')
    # ### end Alembic commands ###