"""add overridden_amount, invoice_status, mdate in invoice table

Revision ID: 39d60138f283
Revises: dce2de08951a
Create Date: 2024-03-17 08:31:52.135191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d60138f283'
down_revision: Union[str, None] = 'dce2de08951a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('mdate', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.func.now()))
    op.add_column('invoices', sa.Column('overridden_amount', sa.Float(), nullable=True, server_default=None))
    op.add_column('invoices', sa.Column('status', sa.String(), nullable=False, server_default='None'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'status')
    op.drop_column('invoices', 'overridden_amount')
    op.drop_column('invoices', 'mdate')
    # ### end Alembic commands ###