"""add vendor bookings table

Revision ID: 40e2e0c7849c
Revises: 39d60138f283
Create Date: 2024-03-27 13:19:53.113808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e2e0c7849c'
down_revision: Union[str, None] = '39d60138f283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_bookings',
    sa.Column('id', sa.BigInteger(), primary_key=True, autoincrement=True),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mdate', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'],)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_bookings')
    # ### end Alembic commands ###
