"""add_room_type_and_no_of_rooms_column_in_hotel_booking_table

Revision ID: 4aba8f3aab34
Revises: 7e9579f5d274
Create Date: 2024-09-12 07:48:38.931701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4aba8f3aab34'
down_revision: Union[str, None] = '7e9579f5d274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel_bookings', sa.Column('no_of_rooms', sa.Integer(), nullable=False))
    op.add_column('hotel_bookings', sa.Column('room_type', sa.String(), nullable=False))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel_bookings', 'room_type')
    op.drop_column('hotel_bookings', 'no_of_rooms')
    # ### end Alembic commands ###
