"""update_column_name_type_in_vendors_table

Revision ID: 5aaf22f5dec2
Revises: bef07f686b83
Create Date: 2024-04-05 07:32:30.231357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aaf22f5dec2'
down_revision: Union[str, None] = 'bef07f686b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vendors', 'vendor_cities', ['city_id'], ['id'])
    op.drop_column('vendors', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.drop_column('vendors', 'city_id')
    # ### end Alembic commands ###
