"""add_po_number_in_invoice_and_address_in_cost_centres_table

Revision ID: 5c282e43af56
Revises: bfc0949c958f
Create Date: 2024-06-26 13:07:40.363645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c282e43af56'
down_revision: Union[str, None] = 'bfc0949c958f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_centres', sa.Column('address', sa.String))
    op.add_column('invoices', sa.Column('po_number', sa.String))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_centres', 'address')
    op.drop_column('invoices', 'po_number')
    # ### end Alembic commands ###
