"""update trip distance, duration in trips and invoices table

Revision ID: 5c99638075a7
Revises: 40e2e0c7849c
Create Date: 2024-03-28 08:26:03.767272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5c99638075a7'
down_revision: Union[str, None] = '40e2e0c7849c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'trip_duration')
    op.drop_column('invoices', 'trip_distance')
    op.add_column('trips', sa.Column('distance', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'duration')
    op.drop_column('trips', 'distance')
    op.add_column('invoices', sa.Column('trip_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('trip_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###