"""add_cron_job

Revision ID: 60cf5bc5aa1b
Revises: a143ea538dd0
Create Date: 2024-08-13 10:25:44.151322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60cf5bc5aa1b'
down_revision: Union[str, None] = 'a143ea538dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_activity_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id']),
    sa.PrimaryKeyConstraint('id')
    )
    # op.execute("""
    # SELECT cron.schedule(
    #     'delete_old_booking_optimal_route', 
    #     '0 0 1 * *', 
    #     'DELETE FROM booking_optimal_routes WHERE cdate < NOW() - INTERVAL ''30 days'''
    # );
    # """)
    # op.execute("""
    # SELECT cron.schedule(
    #     'annual_reset_invoice_seq', 
    #     '0 0 1 4 *', 
    #     'SELECT setval(''yearly_cab_invoice_id_seq'', 1, false);'
    # );
    # """)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_activity_log')
    op.execute("""
        SELECT cron.unschedule('delete_old_booking_optimal_route');
    """)
    op.execute("""
        SELECT cron.unschedule('annual_reset_invoice_seq');
    """)
    # ### end Alembic commands ###
