"""add_po_number_and_description_in_hotel_invoice

Revision ID: 6363841a9dc2
Revises: 7185d7be8b5e
Create Date: 2024-12-03 09:47:29.155338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6363841a9dc2'
down_revision: Union[str, None] = '7185d7be8b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel_invoices', sa.Column('po_number', sa.String(), nullable=True))
    op.add_column('hotel_invoices', sa.Column('description', sa.String(), nullable=True))
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel_invoices', 'description')
    op.drop_column('hotel_invoices', 'po_number')