"""add_pickup_drop_column_in_hotel_bookings

Revision ID: 6749bfe97c5b
Revises: 6a157dea6997
Create Date: 2024-11-25 09:22:41.870654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6749bfe97c5b'
down_revision: Union[str, None] = '6a157dea6997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel_bookings', sa.Column('pickup', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('hotel_bookings', sa.Column('drop', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel_bookings', 'drop')
    op.drop_column('hotel_bookings', 'pickup')