"""add_is_active_column_for_soft_delete

Revision ID: 676bae2d1ec8
Revises: 68a37dbf4495
Create Date: 2024-07-26 07:28:51.882782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676bae2d1ec8'
down_revision: Union[str, None] = '68a37dbf4495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_charges', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')))
    op.add_column('packages', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')))
    op.add_column('plans', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')))
    op.add_column('vehicle_models', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')))
    op.add_column('vehicles', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')))
    op.add_column('vendor_cities', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')))
    op.drop_constraint(
        'uq_package_vehicle_vendor',  # Unique constraint name
        'plans',                     # Table name
        type_='unique'                  # Constraint type
    )
    op.drop_constraint(
        'vehicles_name_key',  # Unique constraint name
        'vehicles',                      # Table name
        type_='unique'                  # Constraint type
    )
    op.drop_constraint(
        'vehicle_models_vehicle_model_key',  # Unique constraint name
        'vehicle_models',                      # Table name
        type_='unique'                  # Constraint type
    )
    op.drop_constraint(
        'vendor_cities_city_key',  # Unique constraint name
        'vendor_cities',                      # Table name
        type_='unique'                  # Constraint type
    )
    op.drop_constraint(
        'uq_distance_duration',  # Unique constraint name
        'packages',                      # Table name
        type_='unique'                  # Constraint type
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_cities', 'is_active')
    op.drop_column('vehicles', 'is_active')
    op.drop_column('vehicle_models', 'is_active')
    op.drop_column('plans', 'is_active')
    op.drop_column('packages', 'is_active')
    op.drop_column('driver_charges', 'is_active')
    op.create_unique_constraint(
        'uq_package_vehicle_vendor',  # Unique constraint name
        'plans',                      # Table name
        ['package_id', 'vehicle_id', 'vendor_id']  # Columns involved in the unique constraint
    )

    op.create_unique_constraint(
        'vehicles_name_key',
        'vehicles',
        ['name']
    )
    op.create_unique_constraint(
        'vehicle_models_vehicle_model_key',
        'vehicle_models',
        ['vehicle_model']
    )
    op.create_unique_constraint(
        'vendor_cities_city_key',
        'vendor_cities',
        ['city']
    )
    op.create_unique_constraint(
        'uq_distance_duration',  # Unique constraint name
        'packages',                      # Table name
        ['distance_kms', 'interval_hrs']           # Columns involved in the unique constraint
    )
    # ### end Alembic commands ###