"""Add hotel_name and supporting_document_url

Revision ID: 687b12f2e8b2
Revises: 24a5d710e3ae
Create Date: 2026-07-09 15:15:20.748584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '687b12f2e8b2'
down_revision: Union[str, None] = '24a5d710e3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_constraint('booking_events_booking_id_fkey', 'booking_events', type_='foreignkey')
    op.create_foreign_key(None, 'booking_events', 'bookings', ['booking_id'], ['id'])
    op.drop_constraint('booking_logs_booking_id_fkey', 'booking_logs', type_='foreignkey')
    op.drop_constraint('booking_logs_guest_id_fkey', 'booking_logs', type_='foreignkey')
    op.drop_constraint('booking_logs_coordinator_id_fkey', 'booking_logs', type_='foreignkey')
    op.drop_constraint('booking_logs_destination_id_fkey', 'booking_logs', type_='foreignkey')
    op.drop_constraint('booking_logs_source_id_fkey', 'booking_logs', type_='foreignkey')
    op.create_foreign_key(None, 'booking_logs', 'locations', ['destination_id'], ['id'])
    op.create_foreign_key(None, 'booking_logs', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'booking_logs', 'coordinators', ['coordinator_id'], ['id'])
    op.create_foreign_key(None, 'booking_logs', 'locations', ['source_id'], ['id'])
    op.drop_column('booking_logs', 'guest_id')
    op.drop_constraint('booking_optimal_routes_booking_id_fkey', 'booking_optimal_routes', type_='foreignkey')
    op.create_foreign_key(None, 'booking_optimal_routes', 'bookings', ['booking_id'], ['id'])
    op.alter_column('bookings', 'bid',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("('BID'::text || nextval('bid_seq'::regclass))"))
    op.alter_column('bookings', 'city_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_constraint('uq_bookings_bid', 'bookings', type_='unique')
    op.create_unique_constraint(None, 'bookings', ['id'])
    op.drop_constraint('cost_centres_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_plan_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_coordinator_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_organizer_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_driver_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('fk_bookings_city_id', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_vendor_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'coordinators', ['coordinator_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'organizers', ['organizer_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'vendor_cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'plans', ['plan_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'cost_centres', ['cost_centre_id'], ['id'])
    op.alter_column('cost_centres', 'code',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('credit_note_invoices', 'taxable_sub_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('credit_note_invoices', 'non_taxable_sub_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint('driver_charges_vehicle_model_id_fkey', 'driver_charges', type_='foreignkey')
    op.drop_constraint('driver_charges_vendor_id_fkey', 'driver_charges', type_='foreignkey')
    op.create_foreign_key(None, 'driver_charges', 'vehicle_models', ['vehicle_model_id'], ['id'])
    op.create_foreign_key(None, 'driver_charges', 'vendors', ['vendor_id'], ['id'])
    op.create_index(op.f('ix_hotel_booking_edit_requests_id'), 'hotel_booking_edit_requests', ['id'], unique=False)
    op.alter_column('hotel_booking_events', 'booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('hotel_booking_guests', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('hotel_booking_guests_guest_id_fkey', 'hotel_booking_guests', type_='foreignkey')
    op.drop_column('hotel_booking_guests', 'guest_id')
    op.alter_column('hotel_bookings', 'cost_centre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('hotel_invoices', sa.Column('hotel_name', sa.String(), nullable=True))
    op.add_column('hotel_invoices', sa.Column('supporting_document_url', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('supporting_document_url', sa.String(), nullable=True))
    op.alter_column('invoices', 'non_taxable_sub_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_constraint('invoices_booking_id_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'bookings', ['booking_id'], ['id'])
    op.drop_constraint('plans_vendor_id_fkey', 'plans', type_='foreignkey')
    op.drop_constraint('plans_package_id_fkey', 'plans', type_='foreignkey')
    op.drop_constraint('plans_vehicle_id_fkey', 'plans', type_='foreignkey')
    op.create_foreign_key(None, 'plans', 'packages', ['package_id'], ['id'])
    op.create_foreign_key(None, 'plans', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'plans', 'vehicles', ['vehicle_id'], ['id'])
    op.drop_constraint('tariff_plans_package_city_vehicle_key_uq', 'tariff_plans', type_='unique')
    op.drop_constraint('tariff_plans_vehicle_id_fkey', 'tariff_plans', type_='foreignkey')
    op.create_foreign_key(None, 'tariff_plans', 'vehicles', ['vehicle_id'], ['id'])
    op.drop_constraint('trip_events_trip_id_fkey', 'trip_events', type_='foreignkey')
    op.create_foreign_key(None, 'trip_events', 'trips', ['trip_id'], ['id'])
    op.drop_constraint('trips_booking_id_fkey', 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'bookings', ['booking_id'], ['id'])
    op.create_unique_constraint(None, 'vehicle_models', ['vehicle_model'])
    op.create_unique_constraint(None, 'vehicles', ['name'])
    op.alter_column('vendor_bookings', 'booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('vendor_bookings_booking_id_fkey', 'vendor_bookings', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_bookings', 'bookings', ['booking_id'], ['id'])
    op.create_unique_constraint(None, 'vendor_cities', ['city'])
    op.drop_constraint('vendor_hotel_bookings_vendor_id_fkey', 'vendor_hotel_bookings', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_hotel_bookings', 'vendors', ['vendor_id'], ['id'])
    op.alter_column('vendor_invoices', 'plan_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('vendor_invoices', 'extra_kms_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_invoices', 'extra_hrs_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint('vendor_invoices_booking_id_fkey', 'vendor_invoices', type_='foreignkey')
    op.drop_constraint('fk_vendor_invoices_plan_id', 'vendor_invoices', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_invoices', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'vendor_invoices', 'plans', ['plan_id'], ['id'])
    op.alter_column('vendors', 'vendor_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'cab'::character varying"))
    op.alter_column('vendors', 'is_third_party',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('vendors_city_id_fkey', 'vendors', type_='foreignkey')
    op.create_foreign_key(None, 'vendors', 'vendor_cities', ['city_id'], ['id'])
    op.drop_constraint('waypoints_booking_id_fkey', 'waypoints', type_='foreignkey')
    op.drop_constraint('waypoints_location_id_fkey', 'waypoints', type_='foreignkey')
    op.drop_constraint('waypoints_guest_id_fkey', 'waypoints', type_='foreignkey')
    op.create_foreign_key(None, 'waypoints', 'locations', ['location_id'], ['id'])
    op.drop_column('waypoints', 'guest_id')
    op.drop_column('waypoints', 'booking_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waypoints', sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('waypoints', sa.Column('guest_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'waypoints', type_='foreignkey')
    op.create_foreign_key('waypoints_guest_id_fkey', 'waypoints', 'guests', ['guest_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('waypoints_location_id_fkey', 'waypoints', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('waypoints_booking_id_fkey', 'waypoints', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.create_foreign_key('vendors_city_id_fkey', 'vendors', 'vendor_cities', ['city_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vendors', 'is_third_party',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('vendors', 'vendor_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'cab'::character varying"))
    op.drop_constraint(None, 'vendor_invoices', type_='foreignkey')
    op.drop_constraint(None, 'vendor_invoices', type_='foreignkey')
    op.create_foreign_key('fk_vendor_invoices_plan_id', 'vendor_invoices', 'plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('vendor_invoices_booking_id_fkey', 'vendor_invoices', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vendor_invoices', 'extra_hrs_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_invoices', 'extra_kms_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_invoices', 'plan_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'vendor_hotel_bookings', type_='foreignkey')
    op.create_foreign_key('vendor_hotel_bookings_vendor_id_fkey', 'vendor_hotel_bookings', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'vendor_cities', type_='unique')
    op.drop_constraint(None, 'vendor_bookings', type_='foreignkey')
    op.create_foreign_key('vendor_bookings_booking_id_fkey', 'vendor_bookings', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vendor_bookings', 'booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_constraint(None, 'vehicle_models', type_='unique')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key('trips_booking_id_fkey', 'trips', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'trip_events', type_='foreignkey')
    op.create_foreign_key('trip_events_trip_id_fkey', 'trip_events', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tariff_plans', type_='foreignkey')
    op.create_foreign_key('tariff_plans_vehicle_id_fkey', 'tariff_plans', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('tariff_plans_package_city_vehicle_key_uq', 'tariff_plans', ['package_id', 'city_id', 'vehicle_id'])
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.create_foreign_key('plans_vehicle_id_fkey', 'plans', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('plans_package_id_fkey', 'plans', 'packages', ['package_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('plans_vendor_id_fkey', 'plans', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_booking_id_fkey', 'invoices', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invoices', 'non_taxable_sub_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_column('invoices', 'supporting_document_url')
    op.drop_column('hotel_invoices', 'supporting_document_url')
    op.drop_column('hotel_invoices', 'hotel_name')
    op.alter_column('hotel_bookings', 'cost_centre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('hotel_booking_guests', sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('hotel_booking_guests_guest_id_fkey', 'hotel_booking_guests', 'guests', ['guest_id'], ['id'], ondelete='CASCADE')
    op.alter_column('hotel_booking_guests', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('hotel_booking_events', 'booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_hotel_booking_edit_requests_id'), table_name='hotel_booking_edit_requests')
    op.drop_constraint(None, 'driver_charges', type_='foreignkey')
    op.drop_constraint(None, 'driver_charges', type_='foreignkey')
    op.create_foreign_key('driver_charges_vendor_id_fkey', 'driver_charges', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('driver_charges_vehicle_model_id_fkey', 'driver_charges', 'vehicle_models', ['vehicle_model_id'], ['id'], ondelete='CASCADE')
    op.alter_column('credit_note_invoices', 'non_taxable_sub_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('credit_note_invoices', 'taxable_sub_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cost_centres', 'code',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_vendor_id_fkey', 'bookings', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_bookings_city_id', 'bookings', 'vendor_cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('bookings_driver_id_fkey', 'bookings', 'drivers', ['driver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bookings_organizer_id_fkey', 'bookings', 'organizers', ['organizer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bookings_coordinator_id_fkey', 'bookings', 'coordinators', ['coordinator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bookings_plan_id_fkey', 'bookings', 'plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cost_centres_fkey', 'bookings', 'cost_centres', ['cost_centre_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bookings', type_='unique')
    op.create_unique_constraint('uq_bookings_bid', 'bookings', ['bid'])
    op.alter_column('bookings', 'city_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('bookings', 'bid',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("('BID'::text || nextval('bid_seq'::regclass))"))
    op.drop_constraint(None, 'booking_optimal_routes', type_='foreignkey')
    op.create_foreign_key('booking_optimal_routes_booking_id_fkey', 'booking_optimal_routes', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.add_column('booking_logs', sa.Column('guest_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'booking_logs', type_='foreignkey')
    op.drop_constraint(None, 'booking_logs', type_='foreignkey')
    op.drop_constraint(None, 'booking_logs', type_='foreignkey')
    op.drop_constraint(None, 'booking_logs', type_='foreignkey')
    op.create_foreign_key('booking_logs_source_id_fkey', 'booking_logs', 'locations', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('booking_logs_destination_id_fkey', 'booking_logs', 'locations', ['destination_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('booking_logs_coordinator_id_fkey', 'booking_logs', 'coordinators', ['coordinator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('booking_logs_guest_id_fkey', 'booking_logs', 'guests', ['guest_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('booking_logs_booking_id_fkey', 'booking_logs', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'booking_events', type_='foreignkey')
    op.create_foreign_key('booking_events_booking_id_fkey', 'booking_events', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
