"""add_unique_constraint_to_cost_centre_code

Revision ID: 68a37dbf4495
Revises: 5c282e43af56
Create Date: 2024-07-02 09:08:58.977496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a37dbf4495'
down_revision: Union[str, None] = '5c282e43af56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cost_centre_code', 'cost_centres', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cost_centre_code', 'cost_centres', type_='unique')