"""add_guest_message_sid_in_booking_logs_table

Revision ID: 69263cb2da53
Revises: 8b00383fb63a
Create Date: 2024-04-30 10:49:40.407407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69263cb2da53'
down_revision: Union[str, None] = '5e6f7bff5f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_logs', sa.Column('guest_message_sid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_logs', 'guest_message_sid')
    # ### end Alembic commands ###