"""add_hotel_booking_edit_request_history

Revision ID: 6a157dea6997
Revises: f4bed4b391e1
Create Date: 2024-10-05 10:51:10.228977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a157dea6997'
down_revision: Union[str, None] = 'f4bed4b391e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_booking_edit_request_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('edit_request_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edit_request_id'], ['hotel_booking_edit_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('hotel_booking_edit_requests', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               )
    op.drop_column('hotel_booking_edit_requests', 'meta_data')
    op.drop_column('hotel_booking_edit_requests', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel_booking_edit_requests', sa.Column('status', sa.VARCHAR(), nullable=False))
    op.add_column('hotel_booking_edit_requests', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('hotel_booking_edit_requests', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               )
    op.drop_table('hotel_booking_edit_request_history')
    # ### end Alembic commands ###
