"""add credit note schema

Revision ID: 6e696a7b0ef1
Revises: 9ef4d00b2305
Create Date: 2025-10-07 02:49:44.618690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e696a7b0ef1'
down_revision: Union[str, None] = '9ef4d00b2305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key('invoices_pkey', 'invoices', ['id'])
    op.create_table('credit_note_invoices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=True),
    sa.Column('credit_note_id', sa.String, nullable=True, unique=True),
    sa.Column('base_fare', sa.Float(), nullable=True),
    sa.Column('extra_kms', sa.Float(), nullable=False),
    sa.Column('extra_hrs', sa.Float(), nullable=False),
    sa.Column('extra_distance_cost', sa.Float(), nullable=False),
    sa.Column('extra_hour_cost', sa.Float(), nullable=False),
    sa.Column('parking_and_toll', sa.Float(), nullable=False),
    sa.Column('miscellaneous', sa.Float(), nullable=False),
    sa.Column('cancellation_amount', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('driver_charge', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=False),
    sa.Column('sgst_amount', sa.Float(), nullable=False),
    sa.Column('taxable_sub_total', sa.Float(), nullable=False),
    sa.Column('non_taxable_sub_total', sa.Float(), nullable=False),
    sa.Column('invoice_amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mdate', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id')
    )
    op.create_index(op.f('ix_credit_note_invoices_id'), 'credit_note_invoices', ['id'], unique=False)
    op.execute('CREATE SEQUENCE yearly_cab_credit_note_id_seq START 1')
    # op.execute("""
    # SELECT cron.schedule(
    #     'annual_reset_cab_credit_note_seq', 
    #     '0 0 1 4 *', 
    #     'SELECT setval(''yearly_cab_credit_note_id_seq'', 1, false);'
    # );
    # """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoices_pkey', 'invoices', type_='primary')
    op.drop_index(op.f('ix_credit_note_invoices_id'), table_name='credit_note_invoices')
    op.drop_table('credit_note_invoices')
    op.execute('DROP SEQUENCE yearly_cab_credit_note_id_seq')
    op.execute("""
        SELECT cron.unschedule('annual_reset_cab_credit_note_seq');
    """)
    # ### end Alembic commands ###
