"""add_hotel_pricing_schema

Revision ID: 7185d7be8b5e
Revises: ea0e7f3f37b8
Create Date: 2024-11-29 07:46:38.219320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7185d7be8b5e'
down_revision: Union[str, None] = 'ea0e7f3f37b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_meal_plans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_room_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_pricing',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('meal_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('room_category_id', sa.BigInteger(), nullable=False),
    sa.Column('single_room_rate', sa.Float(), nullable=False),
    sa.Column('double_room_rate', sa.Float(), nullable=True),
    sa.Column('inclusions', sa.String(), nullable=False),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mdate', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['hotel_meal_plans.id'], ),
    sa.ForeignKeyConstraint(['room_category_id'], ['hotel_room_categories.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotel_pricing')
    op.drop_table('hotel_room_categories')
    op.drop_table('hotel_meal_plans')
    # ### end Alembic commands ###
