"""Add tarrif plans schema

Revision ID: 7e7b4ea916fa
Revises: 162b067e4f75
Create Date: 2025-07-10 11:58:50.274863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e7b4ea916fa'
down_revision: Union[str, None] = '162b067e4f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_plans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('extra_distance_cost', sa.Float(), nullable=False),
    sa.Column('extra_hour_cost', sa.Float(), nullable=False),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mdate', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['vendor_cities.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_plans_id'), 'tariff_plans', ['id'], unique=False)
    op.create_unique_constraint(
        constraint_name='uq_package_city',  # Constraint name
        table_name='tariff_plans',
        columns=['package_id', 'city_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariff_plans_id'), table_name='tariff_plans')
    op.drop_table('tariff_plans')
    op.drop_constraint(
        constraint_name='uq_package_city',
        table_name='tariff_plans',
        type_='unique'
    )
    # ### end Alembic commands ###
