"""add_trip_type_and_city_column_in_hotel_booking_table

Revision ID: 7e9579f5d274
Revises: 238353cc28b8
Create Date: 2024-09-11 18:41:58.572734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7e9579f5d274'
down_revision: Union[str, None] = '238353cc28b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel_bookings', sa.Column('city', sa.String(), nullable=False))
    op.alter_column('hotel_bookings', 'booking_type', new_column_name='trip_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotel_bookings', 'trip_type', new_column_name='booking_type')
    op.drop_column('hotel_bookings', 'city')
    # ### end Alembic commands ###
