"""remove_foreign_key_constraint_from_booking_activity_log

Revision ID: 87abc76193e3
Revises: 6363841a9dc2
Create Date: 2024-12-16 03:18:37.803289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87abc76193e3'
down_revision: Union[str, None] = '6363841a9dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_activity_log', sa.Column('booking_type', sa.String(), nullable=True))
    op.add_column('hotel_bookings', sa.Column('billing_option', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('travel_mode', sa.String(), nullable=True, default='Standard'))
    op.drop_constraint('booking_activity_log_booking_id_fkey', 'booking_activity_log', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('booking_activity_log_booking_id_fkey', 'booking_activity_log', 'bookings', ['booking_id'], ['id'])
    op.drop_column('booking_activity_log', 'booking_type')
    op.drop_column('bookings', 'travel_mode')
    op.drop_column('hotel_bookings', 'billing_option')
    # ### end Alembic commands ###
