"""add cost centre column in booking table

Revision ID: 895cebcc2641
Revises: eb92057a28bf
Create Date: 2024-05-15 09:21:57.553793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '895cebcc2641'
down_revision: Union[str, None] = 'eb92057a28bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_centres', 'is_active')
    op.drop_constraint("cost_centres_pkey", "cost_centres", type_='primary')
    op.drop_column('guests', 'cost_centres')
    op.add_column('cost_centres', sa.Column('gstin_no', sa.String))
    op.add_column('cost_centres', sa.Column('id', sa.INTEGER(), autoincrement=True, primary_key=True))
    op.create_primary_key("cost_centres_pkey", "cost_centres", ["id"])
    op.add_column('bookings', sa.Column('cost_centre_id', sa.INTEGER()))
    op.create_foreign_key(
            "cost_centres_fkey",
            "bookings",
            "cost_centres",
            ["cost_centre_id"],
            ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_centres', sa.Column('is_active', sa.Boolean))
    op.add_column('guests', sa.Column('cost_centres', sa.ARRAY(sa.String(length=255))))
    op.drop_column('cost_centres', 'gstin_no')
    op.drop_column('bookings', 'cost_centre_id')
    op.drop_column('cost_centres', 'id')
    op.create_primary_key("cost_centres_pkey", "cost_centres", ["code"])
    # ### end Alembic commands ###
