"""add_vendor_city_table

Revision ID: 91f8f926ef1d
Revises: 0c0adc36ebac
Create Date: 2024-04-03 12:30:11.816365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f8f926ef1d'
down_revision: Union[str, None] = '9be40118c8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_cities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_cities')
    # ### end Alembic commands ###