"""Add vendor garage location table

Revision ID: 92632c65d990
Revises: 8ae301d270fd
Create Date: 2025-06-11 07:20:50.860517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92632c65d990'
down_revision: Union[str, None] = '8ae301d270fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_garage_locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mdate', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['vendor_cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_garage_locations')
    # ### end Alembic commands ###
