"""Add booking optimal route schema

Revision ID: 94021af9d381
Revises: e993e9d78fb0
Create Date: 2024-03-05 10:03:48.468037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94021af9d381'
down_revision: Union[str, None] = 'dba160bfbc64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_optimal_routes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('depot', sa.String(), nullable=False),
    sa.Column('optimal_route', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_optimal_routes')
    # ### end Alembic commands ###
