"""update_invoices_table

Revision ID: 9be40118c8b7
Revises: 2be879f5fe8a
Create Date: 2024-04-03 18:21:55.502585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be40118c8b7'
down_revision: Union[str, None] = '2be879f5fe8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('base_fare', sa.Float(), nullable=True))
    op.drop_column('invoices', 'driver_cost')
    op.drop_column('invoices', 'extra_hours_cost')
    op.drop_column('invoices', 'extra_kms_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('extra_kms_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('extra_hours_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('driver_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('invoices', 'base_fare')
    # ### end Alembic commands ###
