"""modify_city_column_for_vendor
 
Revision ID: ad7f49dc70f4
Revises: b92d7843a69c
Create Date: 2024-03-28 08:49:21.647065
 
"""
from typing import Sequence, Union
 
from alembic import op
import sqlalchemy as sa
 
 
# revision identifiers, used by Alembic.
revision: str = 'ad7f49dc70f4'
down_revision: Union[str, None] = 'b92d7843a69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
 
 
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###
 
 
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'city')
    # ### end Alembic commands ###