"""added_parking_toll_and_miscellaneous_column_in_invoice_table

Revision ID: af90127cc8d4
Revises: 303d53166552
Create Date: 2024-06-18 14:34:42.856622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af90127cc8d4'
down_revision: Union[str, None] = '303d53166552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('parking_and_toll', sa.DOUBLE_PRECISION(precision=53), server_default='0', nullable=False))
    op.add_column('invoices', sa.Column('miscellaneous', sa.DOUBLE_PRECISION(precision=53), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'miscellaneous')
    op.drop_column('invoices', 'parking_and_toll')