"""add_start_and_end_time_in_trip_table

Revision ID: b0ed2e06114c
Revises: 60cf5bc5aa1b
Create Date: 2024-10-21 15:43:41.950803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0ed2e06114c'
down_revision: Union[str, None] = '60cf5bc5aa1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('starting_time', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('trips', sa.Column('ending_time', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('trips', 'tracker_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('tracker_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('trips', 'ending_time')
    op.drop_column('trips', 'starting_time')
    # ### end Alembic commands ###
