"""add_meta_data_column_in_vendor_bookings

Revision ID: b304fb939439
Revises: fac3551e76a3
Create Date: 2024-04-16 16:49:19.731856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b304fb939439'
down_revision: Union[str, None] = 'fac3551e76a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_bookings', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('vendor_bookings', 'meta_data')
    # ### end Alembic commands ###
