"""Add alternate email and mobile in booking logs

Revision ID: b83ef06521eb
Revises: 0d5fd3eb7a90
Create Date: 2025-08-20 11:42:03.346369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83ef06521eb'
down_revision: Union[str, None] = '0d5fd3eb7a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_logs',
        sa.Column('alternate_email', sa.String(), nullable=True, server_default='')
    )    # ### end Alembic commands ###
    op.add_column('booking_logs',
        sa.Column('alternate_mobile', sa.String(), nullable=True, server_default='')
    )
    op.add_column('locations',
        sa.Column('title', sa.String(), nullable=True, server_default='')
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_logs', 'alternate_email')
    op.drop_column('booking_logs', 'alternate_mobile')
    op.drop_column('locations', 'title')
    # ### end Alembic commands ###
