"""add_vendor_invoices_table

Revision ID: b92d7843a69c
Revises: 5c99638075a7
Create Date: 2024-03-29 04:08:07.846153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b92d7843a69c'
down_revision: Union[str, None] = '5c99638075a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_invoices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('invoice_amount', sa.String(), nullable=False),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_invoices')
    # ### end Alembic commands ###