"""add_driver_charge_in_invoices_table

Revision ID: bef07f686b83
Revises: 91f8f926ef1d
Create Date: 2024-04-04 10:29:54.953710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef07f686b83'
down_revision: Union[str, None] = '91f8f926ef1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('driver_charge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'driver_charge')
    # ### end Alembic commands ###
