"""add_cancellation_amount_for_invoice_table

Revision ID: bfc0949c958f
Revises: af90127cc8d4
Create Date: 2024-06-21 05:21:16.778519

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc0949c958f'
down_revision: Union[str, None] = 'af90127cc8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('cancellation_amount', sa.Float(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'cancellation_amount')

    # ### end Alembic commands ###
