"""add_vendor_hotel_bookings_schema

Revision ID: cd7bb8905c9f
Revises: e3ff3ff0c805
Create Date: 2024-09-20 10:14:39.639921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd7bb8905c9f'
down_revision: Union[str, None] = '4aba8f3aab34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_hotel_bookings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mdate', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['hotel_bookings.id'], name='vendor_hotel_bookings_booking_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='vendor_hotel_bookings_vendor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hotel_bookings', sa.Column('confirmation_no', sa.String()))
    op.create_foreign_key('vendor_bookings_vendor_id_fkey', 'vendor_bookings', 'vendors', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vendor_bookings_vendor_id_fkey', 'vendor_bookings', type_='foreignkey')
    op.drop_table('vendor_hotel_bookings')
    op.drop_column('hotel_bookings', 'confirmation_no')
    # ### end Alembic commands ###
