"""update invoice_description_in_vendor_invoices_table

Revision ID: d5e51087564b
Revises: 69263cb2da53
Create Date: 2024-05-04 16:02:10.447370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e51087564b'
down_revision: Union[str, None] = '69263cb2da53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_invoices', sa.Column('description', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_invoices', 'description')
    # ### end Alembic commands ###