"""add_discount_percent_in_invoice_table

Revision ID: dba160bfbc64
Revises: e993e9d78fb0
Create Date: 2024-03-05 09:49:25.250834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba160bfbc64'
down_revision: Union[str, None] = 'e993e9d78fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('discount_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'discount_percent')
    # ### end Alembic commands ###