"""add trip distance, duration in invoice table

Revision ID: dce2de08951a
Revises: 94021af9d381
Create Date: 2024-03-12 14:38:24.513711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce2de08951a'
down_revision: Union[str, None] = '94021af9d381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('trip_distance', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('trip_duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'trip_duration')
    op.drop_column('invoices', 'trip_distance')
    # ### end Alembic commands ###