"""Add new columns in bookings and booking_logs table

Revision ID: e993e9d78fb0
Revises: ed7d71f8b78a
Create Date: 2024-02-19 10:46:48.540304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e993e9d78fb0'
down_revision: Union[str, None] = 'ed7d71f8b78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('description', sa.String(), nullable=True))
    op.add_column('booking_logs', sa.Column('rank', sa.String(), nullable=True))
    op.add_column('booking_logs', sa.Column('internal_id', sa.String(), nullable=True))
    op.add_column('booking_logs', sa.Column('vessel_name', sa.String(), nullable=True))
    op.add_column('booking_logs', sa.Column('flight_details', sa.String(), nullable=True))
    op.add_column('booking_logs', sa.Column('date_of_duty', sa.TIMESTAMP(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'description')
    op.drop_column('booking_logs', 'date_of_duty')
    op.drop_column('booking_logs', 'flight_details')
    op.drop_column('booking_logs', 'vessel_name')
    op.drop_column('booking_logs', 'internal_id')
    op.drop_column('booking_logs', 'rank')
    # ### end Alembic commands ###