"""add_hotel_invoice_schema

Revision ID: ea0e7f3f37b8
Revises: 6749bfe97c5b
Create Date: 2024-11-03 05:17:31.470393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea0e7f3f37b8'
down_revision: Union[str, None] = '6749bfe97c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_invoices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('invoice_no', sa.String(), nullable=True),
    sa.Column('taxable_amount', sa.Float(), nullable=False),
    sa.Column('non_taxable_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=False),
    sa.Column('sgst_amount', sa.Float(), nullable=False),
    sa.Column('igst_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mdate', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['hotel_bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('hotel_invoice_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sac', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('tax_percent', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('cdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['hotel_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE SEQUENCE hotel_invoice_id_seq START 1')
    # op.execute("""
    # SELECT cron.schedule(
    #     'annual_reset_hotel_invoice_seq', 
    #     '0 0 1 4 *', 
    #     'SELECT setval(''hotel_invoice_id_seq'', 1, false);'
    # );
    # """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotel_invoice_items')
    op.drop_table('hotel_invoices')
    op.execute('DROP SEQUENCE hotel_invoice_id_seq')
    op.execute("""
        SELECT cron.unschedule('annual_reset_hotel_invoice_seq');
    """)
    # ### end Alembic commands ###
