"""add_invoice_id_unique_constraints_in_invoices_table

Revision ID: eb92057a28bf
Revises: d5e51087564b
Create Date: 2024-05-07 06:24:55.941586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb92057a28bf'
down_revision: Union[str, None] = 'd5e51087564b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'invoice_id', existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint('uq_invoice_id', 'invoices', ['invoice_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'invoice_id', existing_type=sa.VARCHAR(), nullable=False)
    op.drop_constraint('uq_invoice_id', 'invoices', type_='unique')
    # ### end Alembic commands ###