"""Modify column char-length in bookings

Revision ID: ed7d71f8b78a
Revises: 14897cf095d5
Create Date: 2024-02-19 08:12:36.725842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7d71f8b78a'
down_revision: Union[str, None] = '14897cf095d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bookings",column_name="cab_type", existing_type=sa.String(10), type_=sa.String)
    op.alter_column("bookings",column_name="type", existing_type=sa.String(10), type_=sa.String)
    op.alter_column("trip_events",column_name="event", existing_type=sa.String(15), type_=sa.String)
    op.alter_column("booking_events",column_name="event", existing_type=sa.String(30), type_=sa.String)
    op.alter_column("invoices",column_name="event", existing_type=sa.String(30), type_=sa.String)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bookings",column_name="cab_type", type_=sa.String(10), existing_type=sa.String)
    op.alter_column("bookings",column_name="type", type_=sa.String(10), existing_type=sa.String)
    op.alter_column("trip_events",column_name="event", type_=sa.String(15), existing_type=sa.String)
    op.alter_column("booking_events",column_name="event", type_=sa.String(30), existing_type=sa.String)
    op.alter_column("invoices",column_name="event", type_=sa.String(30), existing_type=sa.String)
    # ### end Alembic commands ###
