"""add cancellation amount in vendor invoice table

Revision ID: f0a95a57c66e
Revises: 895cebcc2641
Create Date: 2024-05-23 06:46:14.716425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a95a57c66e'
down_revision: Union[str, None] = '895cebcc2641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_invoices', sa.Column('cancellation_amount', sa.Float(), nullable=True))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_invoices', 'cancellation_amount')