"""Add vehicle id in tariff plans

Revision ID: f45fd222f4ae
Revises: b83ef06521eb
Create Date: 2025-09-01 06:25:30.772441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45fd222f4ae'
down_revision: Union[str, None] = 'b83ef06521eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tariff_plans", sa.Column("vehicle_id", sa.BigInteger(), nullable=True)
    )
    # Step 2: Update existing rows with ANY admin_id (first one)
    op.execute(
        """
        UPDATE tariff_plans
        SET vehicle_id = (
            SELECT id FROM vehicles ORDER BY id LIMIT 1
        )
        """
    )

    # Step 3: Set NOT NULL constraint
    op.alter_column("tariff_plans", "vehicle_id", nullable=False)

    # Step 4: Add foreign key constraint (optional but recommended)
    op.create_foreign_key(
        "tariff_plans_vehicle_id_fkey",
        source_table="tariff_plans",
        referent_table="vehicles",
        local_cols=["vehicle_id"],
        remote_cols=["id"],
        ondelete="CASCADE",
    )    
    # ### end Alembic commands ###
    op.drop_constraint("uq_package_city", "tariff_plans", type_="unique")
    op.create_unique_constraint(
        "tariff_plans_package_city_vehicle_key_uq",
        "tariff_plans",
        ["package_id", "city_id", "vehicle_id"]
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tariff_plans", "vehicle_id")
    op.create_unique_constraint(
        "uq_package_city",
        "tariff_plans",
        ["package_id", "vehicle_id"]
    )
    # ### end Alembic commands ###
