"""add_cc_recepients_in_bookings_and_hotel_bookings_table

Revision ID: f4bed4b391e1
Revises: 16ee65e69a0d
Create Date: 2024-10-03 07:26:42.992303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4bed4b391e1'
down_revision: Union[str, None] = '16ee65e69a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_logs', 'cc_recipients')
    op.add_column('bookings', sa.Column('cc_recipients', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('hotel_booking_guests', 'cc_recipients')
    op.add_column('hotel_bookings', sa.Column('cc_recipients', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('hotel_bookings', 'cc_recipients')
    op.add_column('hotel_booking_guests', sa.Column('cc_recipients', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'cc_recipients')
    op.add_column('booking_logs', sa.Column('cc_recipients', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    
    # ### end Alembic commands ###
