"""add_invoice_id_invoices_table

Revision ID: f5c68e494d2e
Revises: 5aaf22f5dec2
Create Date: 2024-04-10 04:31:47.974796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c68e494d2e'
down_revision: Union[str, None] = '5aaf22f5dec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE invoices ALTER COLUMN id TYPE TEXT')
    op.execute('ALTER TABLE invoices ALTER COLUMN id TYPE BIGINT USING (substring(id::text from 1 for 15)::BIGINT)')
    op.execute('CREATE SEQUENCE invoices_id_seq START 1000')
    op.execute('ALTER SEQUENCE invoices_id_seq OWNED BY invoices.id')
    op.execute('ALTER TABLE invoices ALTER COLUMN id SET DEFAULT nextval(\'invoices_id_seq\')')
    op.drop_constraint('invoices_pkey', 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.add_column('invoices', sa.Column('invoice_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.drop_column('invoices', 'invoice_id')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.create_unique_constraint('invoices_pkey', 'invoices', ['id'])
    op.execute('ALTER TABLE invoices ALTER COLUMN id TYPE TEXT')
    op.execute('ALTER TABLE invoices ALTER COLUMN id TYPE UUID USING (uuid_generate_v4())')
    op.execute('ALTER SEQUENCE invoices_id_seq OWNED BY NONE')
    op.execute('DROP SEQUENCE invoices_id_seq')
    # ### end Alembic commands ###
