"""remove_s3_public_url_in_invoices_table

Revision ID: fac3551e76a3
Revises: f5c68e494d2e
Create Date: 2024-04-15 11:41:01.719622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac3551e76a3'
down_revision: Union[str, None] = 'f5c68e494d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 's3_public_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('s3_public_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###