export const ROUTE = {
  LOGIN: "/",
  HOME: "/home",
  TASKS: "tasks",
  BOOKINGS: "new_booking",
  SETTINGS: "settings",
  CITY: "settings/city",
  PASTBOOKINGS: "pastbookings",
  MESSAGE: "message",
  VENDOR: "vendor",
  ORGANIZERS: "organizer",
  BOOKING: "booking",
  BOOKING_DETAILS: "booking/:bid",
  DRIVER_DETAILS: "driver",
  DRIVER_LOGIN: "/drivers/login/:booking_id",
  DRIVER_BOOKING_DETAILS: "drivers/booking",
  DRIVER_TRIP: "drivers/trip",
  DRIVER_TRIP_END: "drivers/trip/end",
  ALL_BOOKINGS: "allbookings",
  INVOICE_REPORT: "invoicereport",
  JOB_REPORT: "jobreport",
  PASSWORD_RESET: "auth/:token",
  COORDINATOR_BOOKINGS:'bookings',
  COORDINATOR_BOOKINGS_DETAILS:'bookings/:bid',
  USER_PROFILE_PAGE:"myprofile",
  TARIFF_PLANS:"tariff_plans"
};
